adjectives = [
    'truculent',
    'fatuous',
    'vainglorious',
    'fatuous',
    'petulant',
    'moribund',
    'jejune',
    'feckless',
    'antiquated',
    'rambunctious',
    'mundane',
    'misshapen',
    'glib',
    'dreary',
    'dopey',
    'devoid',
    'deleterious',
    'degrading',
    'clammy',
    'brazen',
    'indiscreet',
    'indecorous',
    'imbecilic',
    'dysfunctional',
    'dubious',
    'drunken',
    'disreputable',
    'dismal',
    'dim',
    'deficient',
    'deceitful',
    'damned',
    'daft',
    'contrary',
    'churlish',
    'catty',
    'banal',
    'asinine',
    'infantile',
    'lurid',
    'morbid',
    'repugnant',
    'unkempt',
    'vapid',
    'decrepit',
    'malevolent',
    'impertinent',
    'decrepit',
    'grotesque',
    'puerile',
]

nouns = ["airhead",
         "arsehole",
         "ass-kisser",
         "bastard",
         "bimbo",
         "bugger",
         "chicken",
         "dag",
         "dago",
         "deadbeat",
         "dickhead",
         "donkey",
         "dope",
         "dork",
         "dweeb",
         "flake",
         "floozy",
         "freak",
         "fruitcake",
         "gasbag",
         "geek",
         "geezer",
         "git",
         "goose",
         "hick",
         "honky",
         "jerk",
         "klutz",
         "kook",
         "lardass",
         "limey",
         "loudmouth",
         "louse",
         "meathead",
         "nerd",
         "nut",
         "oldbat",
         "pig",
         "poof",
         "prat",
         "rat",
         "redneck",
         "scumbag",
         "sicko",
         "smart-arse",
         "tight-ass",
         "toff",
         "tool",
         "twerp",
         "twit",
         "wanker",
         "weirdo",
         "wimp",
         "yahoo",
         "yob",
         "yokel",
         "zero",
         "slut",
         "d-bag",
         "shit beast",
         "ass clown",
         "waste of air"
         ]

body_parts = [
    "small arms",
    "skinny legs",
    "chicken sticks",
    "twig legs",
    "twig arms",
    "muscleless appendages",
    "breakable ankles",
    "wispy ankles"
]
